package org.jeecg.en;

/**
 * @Description:
 * @Author: qiufeng
 * @Date: Created in 2021/3/18
 */
public enum FlightInfoEnum {

    UU("UU","760","留尼汪","奥斯特拉尔航空公司","Air Austral","http://www.air-austral.com/"),
    SL("SL","310","曼谷","泰国狮子航空公司","Thai Lion Mentari Co., Ltd","http://www.lionairthai.com/en/"),
    Z2("Z2","457","菲律宾马尼拉","亚航飞龙航空公司","Zest Airways","http://www.flyzest.com/"),
    NN("NN","823","莫斯科","维姆航空公司","VIM Airlines","http://www.vim-avia.com/en/"),
//8F("8F","CAD","雅加达","卡迪航空货运公司","Cardig Air","www.cardigair.com"),
    DR("DR","RLH","昆明","瑞丽航空有限公司","Ruili Airlines","www.rlair.net"),
    NL("NL","740","卡拉奇","巴基斯坦沙欣航空公司","SHAHEEN AIR","http://www.shaheenair.com/"),
    O8("O8","874","曼谷","泰国暹罗航空公司","Siam air Transport","http://www.siamair.co.th/"),
    IA("IA","073","巴格达","伊拉克航空公司","IRAQI AIRWAYS","http://www.iraqiairways.com.iq/"),
    XJ("XJ","940","曼谷","泰国亚洲航空有限公司","Thai Airasia X Company Limited","http://www.airasia.com/"),
    KN("KN","822","北京","中国联合航空有限公司","China United Airlines Co.,Ltd.","http://www.flycua.com/"),
    AL("AL","751","开罗","埃及悠闲风行航空公司","Air Leisure","http://www.air-leisure.com/"),
    HZ("HZ","598","海参崴","海参崴航空公司","Aurora Airlines","http://www.vladivostokavia.ru/"),
    QV("QV","627","老挝","老挝航空公司","Lao Airlines","http://www.laoairlines.com"),
    TM("TM","LAM","马普托","莫桑比克航空公司","LAM Mozambique Airlines","www.lam.co.mz"),
    GX("GX","872","中国南宁","广西北部湾航空有限责任公司","Guangxi Beibu Gulf Airlines","http://www.gxairlines.com/"),
    S6("S6","SRR","丹麦","马士基星航航空公司","Star Air (Maersk)","http://www.starair.dk/"),
    GJ("GJ","891","杭州","长龙航空","Loong Airlines(CDC)","http://www.loongair.cn"),
//4J("4J","SMR","杜尚别","塔吉克斯坦索蒙航空公司","SOMON AIR","http://www.somonair.com/"),
    U6("U6","SVR","叶卡捷琳堡","俄罗斯乌拉尔航空公司","Ural Airlines","http://www.uralairlines.ru/"),
    DV("DV","655","哈萨克斯坦奇姆肯特","SCAT航空","SCAT Airlines","http://www.scat.kz/"),
    UP("UP","BHS","拿骚","巴哈马航空公司","Bahamasair","www.bahamasair.com"),
//6N("6N","KRE","哥伦比亚波哥大","苏克雷航空公司","Aerosucre","www.aerosucre.com"),
//7C("7C","806","韩国","韩国济州航空公司","Jeju Air Co. Ltd","http://www.jejuair.net/"),
//4X("4X","805","美国","美国水星航空公司","Mercury Air Cargo, Inc","http://www.mercuryaircargo.com/"),
//2M("2M","391","基希讷乌","摩尔多瓦国际航空公司","Moldavian Airlines","www.mdv.md"),
    W6("W6","WZZ","匈牙利的韦切什","维兹航空公司","wizzair","https://wizzair.com/en-GB/main-page"),
    HB("HB","AAQ","曼谷","亚洲大西洋航空公司","Asia Atlantic Airlines","www.asiaatlanticairlines.com"),
    QH("QH","138","吉尔吉斯斯坦-比什凯克","吉尔吉斯斯坦航空公司","Kyrgyzstan Airline(LYN)","http://www.air.kg"),
    WE("WE","307","美国-迈阿密","圣图伦货运航空公司","Centurion Air Cargo, Inc","http://www.centurioncargo.com/en/"),
    VX("VX","VRD","美国旧金山","维珍美国航空","Virgin America","www.virginamerica.com"),
    OD("OD","816","八打灵再也","马印航空公司","Malindo air","http://www.malindoair.com/"),
    BX("BX","ABL","釜山镇","釜山航空公司","Air Busan","www.airbusan.com"),
    SS("SS","923","巴黎","法国科西嘉国际航空公司","Corsair Airlines","http://www.corsair.fr/"),
    JH("JH","220","美国","美国国际喷气机公司","Amerijet International",""),
    AJ("AJ","ABB","布鲁塞尔","比利时航空公司","AIR BELGIUM","www.brusselsairlines.com"),
    ZB("ZB","BUB","圣丹尼斯","留尼汪波旁航空","Air Bourbon","http://sites.reunionweb.org/air-bourbon/"),
    N4("N4","NWS","莫斯科-谢列梅捷沃国际机场","俄罗斯北风航空公司","NordwindAirlinesLLC","www.nordwindairlines.ru"),
    XW("XW","091","泰国廊曼","泰国酷鸟航空","NokScoot","http://www.nokair.com/nokconnext/aspx/Index.aspx"),
    GB("GB","ABX","美国俄亥俄州的克林顿县","ABX航空","ABX Air","http://www.abxair.com/"),
    R3("R3","SYL","俄罗斯雅库茨克","俄罗斯雅库特航空公司","JSC Airline Yakutia","www.yakutia.aero"),
    WB("WB","459","基加利","卢旺达航空公司","Rwand Air","www.rwandair.com"),
    GI("GI","908","广东梅州","广东龙浩航空有限公司","LONGHAO AIRLINES","www.longhao-air.com"),
    VJ("VJ","VJC","河内","越捷航空","Công ty Cổ phần Hàng không VietJet","http://www.vietjetair.com/sites/web/zh-tw/home"),
//9T("9T","RUN","伊斯坦布尔","土耳其myCARGO货运航空公司","myCARGO Airlines","http://www.mycargo.aero"),
    X5("X5","FBN","科托努","非洲航空公司","Afrique Airlines",""),
    ZI("ZI","AAF","巴黎","法国蓝鹰航空航空公司","Aigle Azur","www.aigle-azur.fr/"),
    GE("GE","TNA","台北市","复兴航空运输股份有限公司","TransAsia Airways","http://gessl.tna.com.tw/"),
    U2("U2","EZY","伦敦","英国易捷航空公司","EasyJet Airline Company Limited","http://www.easyjet.com/cn/"),
    G4("G4","AAY","拉斯维加斯","美国忠实航空公司","Allegiant Air","www.allegiantair.com/"),
//8L("8L","LKE","云南昆明","云南祥鹏航空有限责任公司","Lucky Air","http://www.luckyair.net/"),
    UM("UM","AZM","哈拉雷","津巴布韦航空公司","Air Zimbabwi","www.airzimbabwe.aero/"),
    VY("VY","VLG","巴塞罗那","伏林航空公司","Vueling Airlines","www.vueling.com"),
    JT("JT","990","印度尼西亚雅加达","印度尼西亚狮子航空公司","Lion Airlines","www.lionair.co.id"),
    CF("CF","NKG","北京","中国邮政航空有限公司","China Postal Airlines","http://www.chinapost.com.cn/"),
    JS("JS","KOR","平壤","朝鲜高丽航空商社","Air Koryo","http://www.airkoryo.com.kp/"),
    VI("VI","VDA","乌里扬诺夫斯克","俄罗斯伏尔加第聂伯航空公司","Volga-Dnepr Airline","http://www.airbridgecargo.com/en"),
    Y7("Y7","476","俄罗斯","俄罗斯北方之星航空公司","NordStar Airlines","http://www.nordstar.ru/"),
    PN("PN","847","重庆","西部航空有限责任公司","West Air(CHB)","http://www.westair.cn/"),
    BL("BL","550","越南胡志明市","捷星太平洋航空公司","Jetstar Pacific Airlines(PIC)","http://www.jetstar.com/"),
    TZ("TZ","668","新加坡","新加坡酷航航空公司","Scoot Airways","http://www.flyscoot.com/zh/"),
    TV("TV","088","西藏","西藏航空有限公司","TIBET AIRLINES(TBA)","http://www.tibetairlines.com.cn/"),
    JR("JR","JOY","天津","幸福航空有限公司","Joy Air lines","http://www.joy-air.com/"),
//5B("5B","BSX","柬埔寨-金边","百善航空有限公司","Bassaka air","http://www.bassakaair.com/"),
    BK("BK","866","中国北京","奥凯航空有限公司","Okay Airways Company Limited","http://www.okair.net"),
    ZE("ZE","839","韩国-首尔","韩国易斯达航空有限公司","Eastar Jet airline(ESR)","http://www.eastarjet.com/"),
    G5("G5","987","中国贵阳","华夏航空有限公司","China Express Airlines (HXA)","http://www.chinaexpressair.com/"),
    NS("NS","836","石家庄","河北航空有限公司","Hebei Airlines(DBH)","http://www.hbhk.com.cn/"),
    VW("VW","942","墨西哥城","墨西哥大湖航空公司","Transportes Aeromar, S.A.(TAO)","http://www.aeromar.com.mx/"),
//8Q("8Q","066","伊斯坦布尔","土耳其奥努尔航空公司","Onur Air(OHY)","http://www.onurair.com/"),
    HO("HO","018","上海","上海吉祥航空公司","Juneyao Airlines(DKH)","http://cargo.juneyaoair.com/"),
//3J("3J","535","肯尼亚-内罗毕","朱巴航空公司","Jubba Airways","http://www.jubbaairways.com/"),
    DJ("DJ","888","Djibouti","吉布提航空公司","Air Djibouti(DJU)","http://www.air-djibouti.com/"),
    MN("MN","","南非-约翰内斯堡","南非商务航空公司","Comair Airline(CAW)","http://www.comair.co.za/"),
//9C("9C","089","上海","上海春秋航空公司","Spring Airlines","http://www.ch.com/"),
    IG("IG","191","意大利-奥尔比亚","意大利子午线航空公司","Meridiana Airline(ISS)","https://www.meridiana.it/en/"),
    K6("K6","188","柬埔寨-暹粒","柬埔寨吴哥航空公司","Cambodia Angkor Air","https://www.cambodiaangkorair.com/en"),
    PG("PG","829","曼谷","泰国曼谷航空公司","BANGKOK AIRWAYS(BKP)","http://www.bangkokair.com/eng"),
    UN("UN","670","俄罗斯-莫斯科","俄罗斯洲际航空公司","Transaero Airlines(TSO)","https://www.transaero.ru/"),
//8M("8M","599","缅甸-仰光","缅甸国际航空公司","Myanmar Airways International(MMA)","http://www.maiair.com/"),
    HY("HY","250","塔什干","乌兹别克斯坦航空公司","Uzbekistan Airways(UZB)","https://www.uzairways.com/"),
    LP("LP","544","利马","秘鲁航空公司","LATAM Airlines Peru(LPE)","https://www.latam.com/es_pe/"),
    FV("FV","195-1","莫斯科","俄罗斯国家航空公司","Rossiya Airlines.","http://www.rossiya-airlines.com/"),
    AV("AV","134","波哥大","哥伦比亚国家航空公司","avianca airlines(AVA)","http://www.aviancacargo.com/"),
    FU("FU","028","福州","福州航空有限责任公司","FUZHOU AIRLINE(FZA)","http://www.fuzhou-air.cn/"),
    B2("B2","135","白俄罗斯-明斯克","白俄罗斯航空公司","belavia airlines(BRU)","http://en.belavia.by/online_registration/"),
//3X("3X","435","日本","日本通勒航空公司","Premier Trans Aire",""),
    O3("O3","921","深圳","顺丰航空有限公司","SF Airlines Co. Ltd","http://www.sf-airlines.com/"),
    D7("D7","834","马来西亚吉隆坡","马来西亚亚洲航空公司","air asia airline","http://cargo.airasia.com"),
    FD("FD","843","曼谷","泰国亚洲航空公司","AirAsia","http://cargo.airasia.com/"),
    TR("TR","182","新加坡","欣丰虎航航空公司","Tiger Airways","http://tt.airtiger.com/"),
//6R("6R","873","墨西哥城","墨西哥联合航空公司","AeroUnion","http://www.aerounion.com.mx/eng/tracking/"),
    UW("UW","699","武汉","友和道通航空公司","Uni-top Airlines","http://www.uni-top.com:8081/CargoTracking/queryWaybill.aspx"),
    CA("CA","999","中国-北京","中国国际航空公司","Air China Limited","http://www.airchinacargo.com/en/search_order.php"),
    BG("BG","997","孟加拉国-达卡","孟加拉比曼航空公司","Biman Bangladesh (BBC)","https://www.biman-airlines.com/services/cargo"),
    UX("UX","996","西班牙","欧罗巴航空公司","Air Europa Cargo(AEA)","http://cargo.air-europa.com/ferreret/es/WebPantallaPrincipal.html"),
    D5("D5","992","巴拿马","巴拿马敦豪航空","DHL Aero Expreso (DAE)","http://cargo.air-europa.com/ferreret/es/WebPantallaPrincipal.html"),
    D3("D3","991","迪拜","阿联酋达洛航空公司","Daallo Airlines","http://www.daallo.com/"),
    OZ("OZ","988","韩国-首尔","韩亚航空公司","Asiana Airlines (AAR)","http://www.asianacargo.com/Cn"),
    QO("QO","723","印度-班加罗尔","印度快捷货运航空公司","Quikjet Cargo Airlines Pvt. Ltd","http://www.quikjet.co.in/"),
    OV("OV","960","爱沙尼亚-塔林","爱沙尼亚航空公司","Estonian Air (ELL)","http://www.tradevision.net/appl/fsr.asp?Owner=RES-ELL"),
    JJ("JJ","957","巴西","巴西天马航空公司","TAM Linhas Aereas (TAM)","http://www.datacair.com/QryFlightinfo.aspx"),
    L3("L3","947","危地马拉","危地马拉DHL航空公司","DHL de Guatemala (JOS)","https://aviationcargo.dhl.com/webedit/ACGTracking.asp?WebSite=EU&page=Tracking"),
    V4("V4","946","委内瑞拉","委内瑞拉温萨卡航空公司","Vensecar airline","http://www.vensecar.com/"),
    KZ("KZ","933","日本-东京","日本货运航空公司","Nippon Cargo Airlines(NCA)","http://www.nca.aero/e/index.html"),
    VS("VS","932","英国-伦敦","英国维珍航空公司","Virgin Atlantic Airways","http://www.virgin-atlantic.com/en/gb/cargo/routenetwork/index.jsp"),
    WY("WY","910","马斯喀特","阿曼航空公司","Oman Air (OAS)","http://cargo.omanair.com/en/about-cargo"),
    QN("QN","907","亚美尼亚","亚美尼亚航空公司","Air Armenia(ARR)","http://www.air.am/"),
    LV("LV","400","马尔代夫","马尔代夫美佳航空公司","Mega Maldives airlines","http://www.megamaldivesair.com/"),
    OH("OH","320","美国","太平洋西南航空公司","PSA Airlines","http://www.psaairlines.com/"),
    HU("HU","880","中国-海口","海南航空公司","Hainan Airlines","http://hnacargo.com/Portal/AwbSearch.aspx"),
//3U("3U","876","中国成都","四川航空公司","Sichuan Airlines Co.,Ltd","http://www.scal.com.cn/B2C/News/Freight"),
    Y8("Y8","871","中国-上海","扬子江快运航空有限公司","Yangtze River Express Co. Ltd (YZR)","http://cargo.yzr.com.cn/"),
    VV("VV","870","乌克兰-基辅","乌克兰空中世界航空公司","Aerosvit Airlines","http://www.tradevision.net/appl/fsr.asp?Owner=RES-AEW&Lng=&Doc=/appl/fsr.asp&Func="),
    MY("MY","865","墨西哥-墨西哥","墨西哥麦斯航空公司","MASAir (MWA)","http://www.masair.com/"),
    EV("EV","862","美国-亚特兰大","美国快捷航空公司","ExpressJet Airlines","http://www.expressjet.com/"),
    FK("FK","858","英国","西非航空公司","Africa West (WTA)","http://www.africawest.tg/"),
    HX("HX","851","香港","香港航空有限公司","Hong Kong Airways (CRK)","http://www.hkairlinescargo.com/ENG/track!initTrack.action"),
    OU("OU","831","克罗地亚","克罗地亚航空公司","Croatia Airlines (CTN)","http://www.croatiaairlines.com/Additional-services/cargo/Our-service"),
    R4("R4","827","立陶宛","立陶宛鲁斯航空公司","RUS Aviation","http://www.rusaviation.com/"),
    M6("M6","810","美国","美洲捷运航空公司","Amerijet International (AJT)","https://www.amerijet.com/tracking.aspx"),
    AK("AK","807","马来西亚-吉隆坡","亚洲航空公司","AirAsia Berhad (AXM)","https://cargo.airasia.com/"),
    AE("AE","803","中国-台湾","台湾华信航空公司","Mandarin Airlines (MDA)","http://www.mandarin-airlines.com/cargo_new/index.htm"),
    GS("GS","826","中国-天津","天津航空有限责任公司","Tianjin Airlines(GCR)","http://gs.hnacargo.com/Portal/Default.aspx"),
//1A("1A","790","迈阿密","美国亚当航空公司","Leader Jet International Inc","http://ts.leaderjet.com/cargolinktracking/index.htm"),
    CZ("CZ","784","中国-广州","中国南方航空公司","China Southern Airlines (CSN)","http://tang.cs-air.com/EN/WebFace/Tang.WebFace.Cargo/AgentAwbBrower.aspx"),
    MU("MU","781","中国-上海","中国东方航空公司","China Eastern Airlines (CES)","http://cargo2.ce-air.com/MU/index.aspx"),
    SG("SG","775","印度-哈里亚纳邦","印度森帕蒂航空公司","spicejet airlines","http://scmspicejetlive.cloudapp.net/"),
    FM("FM","774","中国-上海","上海航空公司","Shanghai Airlines (CSH)","http://219.142.127.41/f4/Service/index.aspx?strCul=zh-CN"),
    J2("J2","771","阿塞拜疆-巴库","阿塞拜疆航空公司","Azerbaijan Airline","http://www.cargoupdate.com/tracktrace/"),
    RC("RC","767","丹麦","丹麦大西洋航空公司","Atlantic Airways","https://www.atlantic.fo/default.aspx"),
    TB("TB","754","比利时-扎芬特姆","捷特飞航空公司","Jetairfly(TUB)","http://www.jetairfly.com/en/"),
//4Z("4Z","749","约翰内斯堡","南非支线航空公司","Airlink Airlines","http://www.airlinkcargo.co.za/air_waybill_enquiry.php"),
    AB("AB","745","德国-柏林","德国柏林航空公司","Air Berlin (BER)","http://www.leisurecargo.com/"),
    VN("VN","738","胡志明","越南国家航空公司","Vietnam Airlines","https://www.vietnamairlines.com/en/cargo/shipping-guide/track-your-cargo"),
    MF("MF","731","中国-厦门","厦门航空公司","XiaMen Airlines (CXA)","http://ecargo.xiamenair.com/Pindex.aspx"),
    CW("CW","159","斯洛伐克-布拉迪斯拉发","全球货运航空公司","Air Cargo Global(CCC)","http://www.acg-air.com/"),
    QT("QT","729","比利时","坦帕航空货运公司","Tampa Cargo(TPA)","http://skychain.aviancatacacargonetwork.com:8110/skychain/app"),
    LX("LX","724","瑞士-巴塞尔","瑞士国际航空公司","Swiss International Air Lines (SWR)","http://www.swissworldcargo.com/web/EN/Pages/index.aspx?Country=ROW"),
    MB("MB","716","土耳其","土耳其美尼哥货运航空公司","MNG Cargo Airlines (MNB)","http://www.mngairlines.com/ENG/Homepage.aspx"),
    MR("MR","861","蒙古-乌兰巴托","蒙古匈奴航空公司","Hunnu Air(MML)","http://www.hunnuair.com/en"),
    K5("K5","710","伊朗","阿班航空公司","Aban Air (ABE)","http://www.abanaircargo.com/"),
    KQ("KQ","706","肯尼亚-内罗毕","肯尼亚航空公司","Kendell Airlines (KQA)","http://www.kqcargo.com/"),
//5C("5C","700","中国上海","中国货运航空公司","C.A.L. Cargo Airlines Ltd","www.cal-cargo.com"),
    BR("BR","695","台湾-桃源","台湾长荣航空公司","EVA Airways (EVA)","http://www.brcargo.com/ec_web/"),
    KH("KH","687","美国","阿罗哈航空货运公司","Aloha Air Cargo (AAH)","http://www.alohaaircargo.com/shipment-tracking.html"),
    NX("NX","675","中国-澳门","澳门航空有限公司","Air Macau Company Limited (AMU)","http://122.119.122.44/nx/PublicEng/AwbTracking.aspx?strCul=en"),
    BI("BI","672","文莱 -斯里巴加湾","文莱皇家航空公司","Royal Brunei Airlines (RBA)","http://royalskies.bruneiair.com/Cargo_Services_Airway_bill_search/faces/airway_bill_search.jsp"),
    BT("BT","657","拉脱维亚-里加","波罗的海航空公司","Air Baltic (BTI)","http://www.airbaltic.com/en/cargo-sales-agents-timetable"),
    PX("PX","656","莫尔兹比港","巴布亚新几内亚航空公司","Air Niugini(ANG)","http://airniugini.com.pg/cargo/"),
    TS("TS","649","加拿大","加拿大越洋航空公司","Air Transat (TSC)","http://www.airtransatcargo.com/en"),
    KM("KM","643","马耳他 -鲁卡","马耳他航空公司","Air Malta (AMC)","http://www.cargoupdate.com/tracktrace/"),
    IY("IY","635","也门","也门航空公司","Yemenia Airlines (IYE)","http://www.cargoupdate.com/tracktrace/"),
    GL("GL","631","丹麦-努克","格陵兰航空公司","Air Greenland (GRL)","http://www.airgreenland.gl/cargo/tracking_awb/"),
    DK("DK","630","丹麦-哥本哈根","托马斯库克航空公司","Thomas Cook Airlines Scandinavia (VKG)","http://www.sascargo.com/SASCargo.aspx"),
    MI("MI","629","新加坡","胜安航空公司","silkair singapore airline","http://www.siacargo.com/eservice_siatrk.aspx"),
    PC("PC","624","土耳其-伊斯坦布尔","土耳其飞马航空公司","Pegasus Airlines(PGT)","http://www.pegasuscargo.com/en/default.aspx"),
    FB("FB","623","保加利亚","保加利亚航空公司","Bulgaria Air (LZB)","http://www.datacair.com/QryFlightinfo.aspx"),
    SQ("SQ","618","新加坡","新加坡航空公司","Singapore Airlines","http://www.siacargo.com/"),
    EY("EY","607","阿联酋-阿布扎比","阿联酋阿提哈德航空公司","Etihad cristal cargo (ETD)","http://www.etihadcargo.com/ManageShipment/Pages/ShipmentTracking.aspx"),
    UL("UL","603","斯里兰卡-科伦坡","斯里兰卡航空公司","SriLankan Airlines Limited (ALK)","http://www.srilankanskychain.aero/skychain/app?service=page/nwp:Trackshipmt"),
//9W("9W","589","印度","印度捷特航空公司","Jet Airways (India) Limited (JAI)","http://cargo.jetairways.com/cargoview/"),
    RU("RU","580","俄罗斯","俄罗斯空桥货运航空公司","Airbridge cargo","http://airbridgecargo.com/tracking/"),
    OX("OX","578","泰国","泰国东方航空公司","Orient Thai Airlines (OEA)","https://www.myaat.com/cms/ac/external/imp/ShipmentTrackingSearch"),
//7C*("7C*","575","英国","英国科尼航空公司","Coyne Air(COY)","http://www.coyneair.com/#Tracking"),
    GG("GG","576","美国-北卡罗来纳州格林斯伯勒","美国天空租赁航空","Sky Lease Cargo","www.skyleasecargo.com"),
//9U("9U","572","摩尔多瓦基希讷乌","摩尔多瓦航空公司","Air Moldova (MLD)","http://www.airmoldova.md/cargo-check-en/"),
    PS("PS","566","乌克兰-基辅","乌克兰国际航空公司","Ukraine International Airlines (AUI)","http://cargo.ukraine-international.com/eng/"),
    M2("M2","592","海地","海地森乐仕航空公司","Sunrise Airways","http://www.mariosair.com/searchcargo.php"),
    M3("M3","549","巴西-坎皮纳斯","巴西阿坝萨航空公司","ABSA Aerolinhas Brasileiras (TUS)","http://www.absacargo.com.br/latam/en/"),
    WN("WN","526","美国-达拉斯","美国西南航空公司","Southwest Airlines (SWA)","http://www.swacargo.com/swacargo/trackingTrackShipment.htm"),
    B7("B7","525","中国-台湾","台湾立荣航空公司","EVA Airways (UIA)","https://www.uniair.com.tw/uniairec/index1.aspx"),
    RA("RA","519","尼泊尔","尼泊尔航空公司","Nepal Airlines","http://www.nepalairlines.com.np/?section=cargod&action=browse"),
    G9("G9","514","阿拉伯联合酋长国沙迦","阿拉伯航空公司","Air Arabia (ABY)","http://cargo.airarabia.com/Track.aspx"),
    RJ("RJ","512","约旦-安曼","约旦皇家航空公司","Royal Jordanian","http://www.rj-cargo.com/"),
    SU("SU","555","莫斯科","俄罗斯航空公司","Aeroflot Russian Airlines (AFL)","https://www.aeroflot.ru/personal/cargo_tracking?_preferredLanguage=en"),
//7L("7L","501","阿塞拜疆-巴库","阿塞拜丝路航空公司","Silk Way West Airlines(AZG)","http://www.silkwaywest.com/"),
    W8("W8","489","加拿大","加拿大喷射货运航空公司","Cargojet Airways(CJT)","http://216.123.170.51:8080/Cargojet/Login.jsp"),
//8V("8V","485","肯尼亚","肯尼亚阿斯特拉航空公司","Astral Aviation (ACP)","http://web.ana-aviation.com"),
    ZH("ZH","479","深圳","深圳航空公司","Shenzhen Airlines","http://cargo.shenzhenair.com/"),
    NT("NT","474","加那利群岛","加那利航空公司","Binter Cargo(IBB)","https://tracking.binterswift.com/"),
    KC("KC","465","哈萨克斯坦-阿斯塔纳","阿斯塔纳航空公司","Air Astana","http://www.datacair.com"),
    ZP("ZP","463","阿塞拜疆","阿塞拜疆丝路航空公司","Silk Way Airlines","http://www.cargoupdate.com/tracktrace/"),
    ER("ER","423","德国-北莱茵","德国敦豪航空公司","DHL Airways(DHL)","https://aviationcargo.dhl.com/webedit/ACGSplash.asp"),
    S7("S7","421","俄罗斯-莫斯科","西伯利亚航空公司","Siberia Airlines","http://www.cargoupdate.com/tracktrace/"),
    E6("E6","417","迈阿密","美国伯灵格航空公司","Bringer Air Cargo(BRC)","http://www.bringeraircargo.com/"),
    N8("N8","416","美国","美国国家货运航空公司","National Air Cargo(NCR)","http://www.nationalaircargo.com/"),
//5X("5X","406","美国","UPS联合包裹航空公司","United Parcel Service","http://www.ups.com/aircargo/using/services/actracking/actracking.html"),
    PO("PO","403","美国-纽约州-帕切斯","美国博立航空公司","Polar Air Cargo","http://www.polaraircargo.com/"),
    A3("A3","390","希腊-雅典","希腊爱琴海航空公司","Aegean Airlines (AEE)","http://www.cargoupdate.com/tracktrace/"),
    KX("KX","378","开曼群岛","开曼航空公司","Cayman Airways (CAY)","http://www.caymancargo.com/"),
//5Y("5Y","369","美国","美国亚特拉斯航空公司","Atlas Air(GTI)","http://www.polaraircargo.com/tracking.asp"),
    C8("C8","356","卢森堡","意大利卢森堡国际货运航空公司","Cargolux Italia (ESF)","http://www.cargolux-italia.com/"),
    E7("E7","355","墨西哥","墨西哥邮件空运航空公司","Estafeta Carga Aerea (ESF)","http://www.estafeta.com/services/cargo/air-cargo/tracking.aspx"),
    NC("NC","345","美国","美国北方货运航空公司","Northern Air Cargo (NAC)","http://www.northernaircargo.com/"),
    S4("S4","331","葡萄牙-蓬塔德尔加达","葡萄牙亚速尔国际航空公司","Sata international airlines","http://www.sata.pt/en/other-services/cargo-tracking"),
    DY("DY","328","挪威-奥斯陆","挪威航空公司","Norwegian Air Shuttle (NAX)","http://www.norwegian.no/"),
    SC("SC","324","中国-济南","山东航空公司","Shandong Airlines","http://www.shandongair.com.cn/web/shair_zh/hdcx"),
    QP("QP","321","德国","德国星光航空公司","Starlight Airlines","http://www.starlightairline.com/track.aspx"),
    CC("CC","318","冰岛","冰岛亚特兰大航空公司","Air Atlanta Icelandic (ABD)","http://www.cargoupdate.com/tracktrace/"),
//3A("3A","317","美国","联盟航空公司","Alliance Airlines","http://www.allianceground.com/"),
//6E("6E","312","印度","印地高航空公司","IndiGo CarGo","http://cargo.goindigo.in/"),
//    WE*("WE*","909","泰国-曼谷","泰国泰微笑航空公司","Thai Smile Airways","https://www.thaismileair.com/"),
    OO("OO","302","美国","美国天西航空公司","Sky West Airlines (SKW)","http://www.skywest.com/"),
//5S("5S","301","利比亚","全球航空服务公司","Global Aviation and Services (GAK)","http://www.global-aviationgroup.com/"),
    CI("CI","297","中国-台湾","台湾中华航空股份有限公司","China Airlines","https://cargo.china-airlines.com/CCNet/pgHome/index.aspx"),
    LD("LD","288","中国香港","香港华民航空公司","Air Hong Kong (AHK)","http://www.hactl.com/webapp/hactlpbf/pbfcontroller/HDCACT"),
    RO("RO","281","罗马尼亚","罗马尼亚航空公司","TAROM Romanian Air Transport","http://www.tarom.ro/en/services/cargo/track-trace/"),
    B6("B6","279","美国-纽约","捷蓝航空公司","JetBlue Airways","https://icargonet.ibsplc.aero/b6portal/login.jsp"),
    K4("K4","272","美国","卡利塔航空公司","Kalitta Air (CKS)","http://www.kalittacargo.com/"),
    TL("TL","270","黎巴嫩-贝鲁特","跨地中海航空公司","Trans Mediterranean Airways(TMA)","http://www.cargoserv.com/tracking.asp?Carrier=TL&Pfx=270"),
    L8("L8","348","德国-杜塞尔多夫","德国雷苏航空公司","Leisure Cargo","http://www.leisurecargo.com/"),
    FE("FE","265","中国台北","远东航空公司","Far Eastern Air Transport (FEA)","http://www.cargoserv.com/tracking.asp?Carrier=EF&Pfx=265"),
    MD("MD","258","马达加斯加","马达加斯加航空公司","Air Madagascar (MDG)","http://www.airmadagascar.com/"),
    OS("OS","257","奥地利","奥地利航空公司","Austrian Cargo (AUA)","http://www.lhcargo.com/"),
    MK("MK","239","毛里求斯-路易港","毛里求斯航空有限公司","Air Mauritius (MAU)","http://www.airmauritius.com/cargotracking.htm"),
    BD("BD","236","英国","英国大陆航空公司","British Midland Airways Ltd. (BMA)","https://www.descartes.com/"),
    TK("TK","235","土耳其-伊斯坦布尔","土耳其航空公司","Turkish Airlines(THY)","http://www.turkishcargo.com.tr/en/e-cargo/cargo-tracking"),
    JD("JD","898","北京","北京首都航空公司","Beijing Capital Airlines","http://www.jdair.net/"),
    MH("MH","232","马来西亚-吉隆坡","马来西亚航空公司","Malaysian Airline System Berhad (MAS)","http://www.maskargo.com/ecommerce/ost"),
    NG("NG","231","奥地利-维也纳","奥地利劳达航空公司","Lauda Air (LDA)","http://lufthansa-cargo.com/"),
    CM("CM","230","巴拿马","巴拿马航空公司","COPA Airlines (CMP)","http://www.copacargo.com/homepage.aspx?lang=en"),
    KU("KU","229","科威特","科威特航空公司","Kuwait Airways (KAC)","http://www.kuwaitairways.com/en/is/gs/cargo/Pages/tracking.aspx"),
    TG("TG","217","泰国-曼谷","泰国航空公司","Thai Airways(THA)","http://chorus.thaicargo.com/skychain/app"),
    PK("PK","214","巴基斯坦","巴基斯坦航空公司","Pakistan International Airlines (PIA)","http://www.cargoupdate.com/tracktrace/"),
    NH("NH","205","日本-东京","日本全日空航空公司","ANA All Nippon Airways","http://www.anacargo.jp/en/int/"),
//5J("5J","203","中国","菲律宾宿务太平洋航空公司","Cebu Pacific Air (CPI)","http://www.cebupacificaircargo.com/en/awb-tracking"),
    TA("TA","202","萨尔瓦多","塔卡国际航空公司","TACA Airlines(TAI)","http://skychain.aviancatacacargonetwork.com:8110/skychain/app?service=page/nwp:Trackshipmt"),
    JM("JM","201","牙买加-金斯敦","牙买加航空有限公司","Air Jamaica (AJM)","http://www.airjamaica.com/track.aspx"),
    Z8("Z8","195","俄罗斯-圣彼得堡","俄罗斯普尔科沃航空公司","Pulkovo Aviation Enterprise","http://www.selectairlinemanagement.com/Sam/index.jsp"),
    SW("SW","186","纳米比亚-温得和克","纳米比亚航空公司","Air Namibia (NMB)","http://www.selectairlinemanagement.com/Sam/index.jsp"),
    KE("KE","180","韩国","大韩航空公司","Korean Air Lines Co. Ltd. (KAL)","http://cargo.koreanair.com/kor/main_page.jsp"),
    EK("EK","176","阿联酋-迪拜","阿联酋航空公司","Emirates Airlines","http://www.sky-cargo.com/english/index.aspx"),
    HA("HA","173","美国-夏威夷","夏威夷航空公司","Hawaiian Airlines (HAL)","https://icargonet.ibsplc.aero/haportal/jsp/operations/shipment/AWBTracking.jsf"),
    CV("CV","172","卢森堡-芬德尔机场","卢森堡国际货运航空公司","Cargolux Airlines International (CVA)","http://www.cargolux.com/"),
    QM("QM","167","马拉维-布兰太尔","马拉维航空公司","Air Malawi (AML)","http://web.ana-aviation.com"),
    JP("JP","165","斯洛文尼亚","斯洛文尼亚国际航空公司","Adria Airways-The Airline of Slovenia (ADR)","http://www.adria.si/en/services/cargo/"),
//3V("3V","163","比利时","比利时TNT航空公司","TNT Airways","http://www.tnt.com/webtracker/tracker.do?navigation=1&respLang=en&respCountry=GENERIC&genericSiteIdent="),
    CX("CX","160","中国-香港","香港国泰航空有限公司","Cathay Pacific Airways Ltd. (CPA)","http://www.cathaypacificcargo.com/"),
    QR("QR","157","卡塔尔-多哈","卡塔尔航空公司","Qatar Airways(QTR)","http://www.qrcargo.com/"),
    ES("ES","155","中国-北京","敦豪航空公司(DHX)","DHL International E.C.(DHX)","https://aviationcargo.dhl.com/webedit/ACGTracking.asp"),
    AT("AT","147","摩洛哥-卡萨布兰卡","摩洛哥皇家航空公司","Royal Air Maroc (RAM)","http://apps.traxon.com/ram.htm"),
    UC("UC","145","智利","智利拉塔姆航空公司","LATAM Cargo Chile(LCO)","http://www.lancargo.com/"),
    FZ("FZ","141","迪拜","迪拜航空公司","Flydubai (FDB)","http://skychain.emirates.com/skychain/app?service=page/nwp:Trackshipmt"),
    LI("LI","140","秘鲁","秘鲁利亚塔航空公司","LIAT Airlines(LIA)","http://www.liat.com/"),
    AM("AM","139","墨西哥","墨西哥航空公司","Aeromexico Cargo (AMX)","http://www.skyteamcargo.com/"),
    CU("CU","136","古巴","古巴航空公司","Cubana de Aviacion S.A. (CUB)","http://www.selectairlinemanagement.com/Sam/TrackerNoLogin.jsp"),
    MX("MX","132","墨西哥","墨西哥联运航空公司","Aeroméxico Cargo (MXA)","http://www.aeromexicocargo.com.mx/"),
    JL("JL","131","日本-东京","日本航空公司","Japan Airlines Company Ltd. (JAL)","http://www.jal.co.jp/jalcargo/"),
    MP("MP","129","荷兰-阿姆斯特丹","荷兰马丁航空公司","Martinair Cargo (MPH)","http://www.af-klm.com/cargo/portalb2b/home"),
    UO("UO","128","中国-香港","香港快运航空公司","HONGKONG EXPRESS(HKE)","http://www.hactl.com/en-us/home.aspx"),
    GA("GA","126","印尼-雅加达","印尼鹰航航空","Garuda Indonesia (GIA)","http://cargo.garuda-indonesia.com"),
    BA("BA","125","英国-伦敦","英国航空公司","British Airways p.l.c. (BAW)","http://www.baworldcargo.com/tracking/results.jsp"),
    AH("AH","124","阿尔及利亚-阿尔及尔","阿尔及利亚航空公司","Air Algerie (DAH)","http://www.cargoupdate.com/tracktrace/"),
    LM("LM","682","英国","洛根航空公司","Loganair Limited","http://www.loganair.co.uk/"),
    DT("DT","118","安哥拉-卢安达","安哥拉航空公司","TAAG - Linhas Aereas de Angola (DTA)","http://www.cargoupdate.com/tracktrace/"),
    SK("SK","117","瑞典斯德哥尔摩","北欧航空公司","scandinavian airlines system","http://www.sascargo.com/SASCargo.aspx?NavID=90"),
    JU("JU","115","贝尔格莱德","塞尔维亚航空公司","Jugoslovenski Aerotransport (JAT)","http://www.cargoupdate.com/tracktrace/"),
    LY("LY","114","以色列","以色列航空公司","El Al Israel Airlines (ELY)","http://www.elal.co.il/ELAL/English/ELALCargo/"),
    CK("CK","112","中国-上海","中国东方货运航空公司","China Cargo Airlines LTD. (CKK)","http://cargo.ce-air.com/mu/Service/getawbinfo.aspx?strCul=zh-CN"),
    FI("FI","108","冰岛","冰岛航空公司","Iceland air (ICE)","http://www.cargoupdate.com/tracktrace/"),
    BW("BW","106","西班牙","西印度群岛航空公司","BWIA West Indies Airways Limited (BWA)","http://www.caribbean-airlines.com/index.php/products-a-services/cargo-a-jet-pak/track-shipments"),
    AY("AY","105","芬兰","芬兰航空公司","Finnair Oyj (FIN)","http://www.finnaircargo.com/en/"),
    AI("AI","098","印度","印度航空公司","Air India (AIC)","http://airindia.in/SBCMS/Webpages/Cargo-Tracking.aspx?MID=200"),
    IR("IR","096","伊朗","伊朗航空公司","Iran air (IRA)","http://www.cargoserv.com/tracking.asp?Carrier=IR&Pfx=096"),
    IT("IT","090","印度-班加罗尔","翠鸟航空有限公司","Kingfisher Airlines (KFR)","http://www.kingfishercargo.com/"),
    NZ("NZ","086","新西兰","新西兰航空公司","Air New Zealand (ANZ)","http://www.airnewzealand.co.uk/international-cargo#"),
    SA("SA","083","南非","南非航空公司","South African Airways","http://www.flysaa.com/za/en/Saa_Cargo_new/flysaa_cargo_track_a_shipment.html"),
    SN("SN","082","布鲁塞尔","比利时布鲁塞尔航空公司","Brussels Airlines","http://company.brusselsairlines.com/en_be/corp/b2b-and-corporate/brussels-airlines-cargo/track-and-trace.aspx"),
    QF("QF","081","美国","澳洲航空公司","Qantas Airways (QFA)","https://www.qantas.com.au/qfreight/qfe/online-tracking-portal/global/en"),
    LO("LO","080","波兰-华沙","波兰航空公司","Lot Polish Airlines (LOT)","http://ebooking.champ.aero/trace/LO/trace.asp"),
    PR("PR","079","菲律宾","菲律宾航空公司","Philippine airlines (PAL)","http://www.cargoupdate.com/tracktrace/"),
    MS("MS","077","埃及","埃及航空公司","Egypt airline(MSR)","http://egyptair-cargo.com/cargo/tracking.htm"),
    LQ("LQ","076","黎巴嫩","黎巴嫩航空公司","lebanese airlines(LAQ)","http://www.mea.com.lb/English/PlanBook/Pages/Cargo.aspx"),
    IB("IB","075","西班牙","西班牙航空公司","Iberia Lineas(IBE)","http://www.cargoserv.com/tracking.asp?Carrier=IB&Pfx=075"),
    KL("KL","074","荷兰","荷兰皇家航空公司","KLM (KLM)","https://afklcargo.com/WW/en/local/app/tnt/trackntrace.jsp"),
    GF("GF","072","巴林","海湾航空公司","Gulf Air (GFA)","http://www.gfcargo.com/English/Pages/default.aspx"),
    ET("ET","071","埃塞俄比亚","埃塞俄比亚航空公司","Ethiopian airlines (ETH)","https://www.myaat.com/cms/ac/external/imp/ShipmentTrackingSearch"),
    RB("RB","070","叙利亚","叙利亚阿拉伯航空公司","Syrian Arab Airlines","http://www.cargoupdate.com/tracktrace/"),
    SV("SV","065","沙特阿拉伯-利雅得","沙特阿拉伯航空公司","Saudi Arabian Airlines","http://www.saudiacargo.com/"),
    OK("OK","064","捷克","捷克航空公司","CSA Czech Airlines (CSA)","http://cargo.czechairlines.com/en/cargo/cargo_home.htm"),
    HM("HM","061","塞舌尔","塞舌尔航空公司","Air Seychelles (SEY)","http://www.cargoserv.com/tracking.asp?Carrier=HM&Pfx=061"),
    AF("AF","057","法国","法国航空公司","Air France (AFR)","http://www.af-klm.com/cargo/b2b/wps/portal/b2b"),
    AZ("AZ","055","意大利","意大利航空公司","Alitalia (AZA)","http://www.alitaliacargo.it/en/index.html"),
    EI("EI","053","爱尔兰-都柏林","爱尔兰航空公司","Aer Lingus (EIN)","http://www.aerlinguscargo.com/"),
    OA("OA","050","希腊","希腊国营奥林匹克航空公司","Olympic Airways (OAL)","http://www.olympicair.com/Cargo.aspx?a_id=1660"),
    CY("CY","048","塞浦路斯","塞浦路斯航空公司","Cyprus Airways (CYP)","http://www.cargoupdate.com/tracktrace/"),
    TP("TP","047","葡萄牙","葡萄牙航空公司","TAP AIR PORTUQAL(TAP)","http://www.tapcargo.com/en/Homepage/"),
    LA("LA","045","智利-圣地亚哥","智利航空公司","LATAM Airlines Group(LAN)","http://www.lancargo.com/"),
    AR("AR","044","阿根廷-布宜诺斯艾利斯","阿根廷航空公司","AEROLINEAS (ARG)","http://www.aerolineas.com.ar/Arg/main.asp?idSitio=US&idPagina=186&idIdioma=en"),
    KA("KA","043","中国-香港","港龙航空公司","Dragon Air (HDA)","http://www.dragonaircargo.com/usrapps/identity/home.aspx"),
    RG("RG","042","巴西里约热内卢","巴西约格朗德航空公司","Varig airline","http://apps.traxon.com/rg042.htm"),
//3K("3K","041","新加坡","捷星亚洲航空","Jetstar Asia Airways","http://www.cargoserv.com/tracking.asp?Carrier=QF&Pfx=041"),
    QC("QC","040","喀麦隆","喀麦隆航空公司","Camair-Co","http://camair-co.tdacermai.net/"),
    US("US","037","美国-得克萨斯-沃斯堡","美国航空公司","US Airways (USA)","http://www.usairways.com/en-US/traveltools/cargo/ustrackshipments.html"),
    AS("AS","027","美国-阿拉斯加","阿拉斯加航空公司","Alaska Airlines (ASA)","http://cargo.alaskaair.com/awbtrackui/awbtrack.aspx"),
    FX("FX","023","美国","美国联邦航空公司","Fedex","http://www.fedex.com/Tracking"),
    LH("LH","020","德国-法兰克福","德国汉莎航空公司","Lufthansa Cargo AG (DLH)","http://tracking.lhcargo.com/trackit/awb.trackit"),
    CP("CP","003","加拿大","加拿大国际航空公司","Canadian Airlines","http://tracking.lhcargo.com/trackit/awb.trackit"),
    UA("UA","016","美国-芝加哥","美国联合航空公司","United Airlines (UAL)","http://booking.unitedcargo.com/skychain/app?service=page/nwp:Trackshipmt"),
    AC("AC","014","加拿大-蒙特利尔","加拿大航空公司","Air Canada (ACA)","http://www.aircanada.com/cargo/en/"),
    GY("GY","013","加蓬利伯维尔","加蓬航空公司","Gabon Airlines (GBK)","http://www.datacair.com/QryFlightinfo.aspx"),
    NW("NW","012","美国-明尼苏达-伊根","美国西北航空公司","Northwest Airlines (NWA)","http://www.deltacargo.com/"),
    DL("DL","006","美国-乔治亚-亚特兰大","美国达美航空公司","Delta Air Lines (DAL)","https://www.deltacargo.com/"),
    CO("CO","005","美国-得克萨斯-休斯敦","美国大陆航空公司","Continental Airlines (COA)","http://cargo.cocargo.com/cargo/track/default.aspx"),
    AA("AA","001","美国德州沃斯堡","美国美洲航空公司","American Airlines(AAL)","https://www.aacargo.com/AACargo/tracking"),
    W5("W5","000","伊朗","伊朗马汉航空公司","Mahan Airlines","http://mahan-cargo.com/");


    private String website;
    private String flightName;
    private String flightEnglishName;
    private String twoCode;
    private String threeCode;
    private String location;

//    FlightInfoEnum(String prefix, String flightName, String flightEnglishName, String twoCode, String threeCode, String location) {
    FlightInfoEnum(String twoCode, String threeCode, String location, String flightName, String flightEnglishName, String website) {
        this.website = website;
        this.flightName = flightName;
        this.flightEnglishName = flightEnglishName;
        this.twoCode = twoCode;
        this.threeCode = threeCode;
        this.location = location;
    }

    public static FlightInfoEnum toNum(String threeCode) throws Exception {
        FlightInfoEnum[] var = values();
        for (int i = 0; i < var.length; i++) {
            FlightInfoEnum en = var[i];
            if (en.threeCode.equals(threeCode)) {
                return en;
            }
        }
        throw new Exception("运单航司不存在，请检查数据！");
    }

    public String getFlightName() {
        return flightName;
    }

    public String getWebsite() {
        return website;
    }

    public String getFlightEnglishName() {
        return flightEnglishName;
    }

    public String getTwoCode() {
        return twoCode;
    }

    public String getThreeCode() {
        return threeCode;
    }

    public String getLocation() {
        return location;
    }
}
